// skills/SkillAttributeData.js — Tabela REAL de skills do cliente PC 5.2
// (MuPromax). GERADO de Data/Local/Por/skill_por.bmd (48004 bytes =
// 600 registros × 80B + DWORD checksum) via tools/gen-skill-attribute-table.mjs.
//
// AUTORIDADE PC: OpenSkillScript (ZzzInfomation.cpp:256-299) — BuxConvert XOR
// FC/CF/AB com key reiniciada POR REGISTRO; SKILL_ATTRIBUTE (_struct.h:301-327):
//   Name[32]@0  Level(BYTE)@32  Damage(WORD)@34  Mana(WORD)@36
//   AbilityGuage(WORD)@38  Distance(BYTE)@40  Delay(int)@44  Energy(int)@48
//   Charisma(WORD)@52  MasteryType(B)@54  SkillUseType(B)@55  SkillBrand(B)@56
//   KillCount(B)@57  RequireDutyClass[3]@58  RequireClass[7]@61
//   Magic_Icon(WORD)@68  TypeSkill(B)@70  Strength(int)@72  Dexterity(int)@76
//
// O índice do registro = wire-type AT_SKILL_* (SkillManager.h) — é o MESMO
// Type que o servidor envia no F3:11 magicList (WSclient.cpp:1179:
// CharacterAttribute->Skill[Index] = Type). ReceiveMagicList também usa
// SkillAttribute[SkillType] para ícone/usabilidade (WSclient.cpp:1237).
// Nomes PT-BR vindos do arquivo REAL — zero invenção.

export const SKILL_ATTRIBUTE_STRIDE = 80;
export const SKILL_ATTRIBUTE_COUNT = 600;
const BUX = [0xFC, 0xCF, 0xAB];

/** Porte de BuxConvert + parse de um registro (OpenSkillScript). */
export function decodeSkillAttributeRecord(src, offset = 0) {
  const rec = new Uint8Array(SKILL_ATTRIBUTE_STRIDE);
  for (let i = 0; i < SKILL_ATTRIBUTE_STRIDE; i++) rec[i] = src[offset + i] ^ BUX[i % 3];
  let name = '';
  for (let i = 0; i < 32; i++) { const c = rec[i]; if (c === 0) break; name += String.fromCharCode(c); }
  if (!name) return null;
  const dv = rec;
  return {
    type: 0, // preenchido pelo caller (índice do registro)
    name,
    level: dv[32],
    damage: dv[34] | (dv[35] << 8),
    mana: dv[36] | (dv[37] << 8),
    distance: dv[40],
    delay: dv[44] | (dv[45] << 8) | (dv[46] << 16) | (dv[47] << 24),
    energy: dv[48] | (dv[49] << 8) | (dv[50] << 16) | (dv[51] << 24),
    masteryType: dv[54],
    skillUseType: dv[55],
    magicIcon: dv[68] | (dv[69] << 8),
    typeSkill: dv[70],
  };
}

/** Porte de OpenSkillScript: decodifica o buffer inteiro do skill_*.bmd. */
export function decodeSkillAttributeScript(buffer) {
  const src = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
  if (src.length < SKILL_ATTRIBUTE_STRIDE * SKILL_ATTRIBUTE_COUNT) {
    throw new Error(`skill.bmd curto: ${src.length} (mínimo ${SKILL_ATTRIBUTE_STRIDE * SKILL_ATTRIBUTE_COUNT})`);
  }
  const out = new Array(SKILL_ATTRIBUTE_COUNT).fill(null);
  for (let r = 0; r < SKILL_ATTRIBUTE_COUNT; r++) {
    const rec = decodeSkillAttributeRecord(src, r * SKILL_ATTRIBUTE_STRIDE);
    if (rec) { rec.type = r; out[r] = rec; }
  }
  return out;
}

// Tabela embutida (fallback offline) — mesmos dados do arquivo real, extraída
// em 2026-09-25. No runtime o loader prefere o
// arquivo vivo servido pelo asset-server (Local/Por/skill_por.bmd) e usa esta
// tabela só se o fetch falhar (mesma origem, zero invenção).
export const SKILL_ATTRIBUTE_TABLE = [
 {
  "type": 1,
  "name": "Veneno",
  "level": 30,
  "damage": 12,
  "mana": 42,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 1,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 2,
  "name": "Meteorito",
  "level": 21,
  "damage": 21,
  "mana": 12,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 4,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 3,
  "name": "Raio",
  "level": 13,
  "damage": 17,
  "mana": 15,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 2,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 4,
  "name": "Bola de fogo",
  "level": 5,
  "damage": 8,
  "mana": 3,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 5,
  "name": "Chama",
  "level": 35,
  "damage": 25,
  "mana": 50,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 6,
  "name": "Teletransporte",
  "level": 17,
  "damage": 0,
  "mana": 30,
  "distance": 6,
  "delay": 3000,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 7,
  "name": "Gelo",
  "level": 25,
  "damage": 10,
  "mana": 38,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 8,
  "name": "Twister",
  "level": 40,
  "damage": 35,
  "mana": 60,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 5,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 9,
  "name": "Espírito maligno",
  "level": 50,
  "damage": 45,
  "mana": 90,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 10,
  "name": "Fogo do inferno",
  "level": 60,
  "damage": 120,
  "mana": 160,
  "distance": 0,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 11,
  "name": "Onda de poder",
  "level": 9,
  "damage": 14,
  "mana": 5,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 12,
  "name": "Raio de água",
  "level": 74,
  "damage": 80,
  "mana": 140,
  "distance": 6,
  "delay": 0,
  "energy": 110,
  "masteryType": 6,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 13,
  "name": "Queda do cometa",
  "level": 80,
  "damage": 70,
  "mana": 150,
  "distance": 3,
  "delay": 0,
  "energy": 150,
  "masteryType": 2,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 14,
  "name": "Inferno",
  "level": 88,
  "damage": 100,
  "mana": 200,
  "distance": 0,
  "delay": 0,
  "energy": 200,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 15,
  "name": "Teletransportar aliado",
  "level": 83,
  "damage": 0,
  "mana": 90,
  "distance": 6,
  "delay": 0,
  "energy": 188,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 16,
  "name": "Barreira da alma",
  "level": 77,
  "damage": 0,
  "mana": 70,
  "distance": 6,
  "delay": 0,
  "energy": 126,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 17,
  "name": "Bola de energia",
  "level": 2,
  "damage": 3,
  "mana": 1,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 18,
  "name": "Defesa",
  "level": 0,
  "damage": 0,
  "mana": 30,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 19,
  "name": "Golpe em queda",
  "level": 0,
  "damage": 0,
  "mana": 9,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 20,
  "name": "Impulso",
  "level": 0,
  "damage": 0,
  "mana": 9,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 21,
  "name": "Gancho",
  "level": 0,
  "damage": 0,
  "mana": 8,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 22,
  "name": "Ciclone",
  "level": 0,
  "damage": 0,
  "mana": 9,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 23,
  "name": "Golpe",
  "level": 0,
  "damage": 0,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 24,
  "name": "Tiro triplo",
  "level": 0,
  "damage": 0,
  "mana": 5,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 26,
  "name": "Cura",
  "level": 8,
  "damage": 0,
  "mana": 20,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 3
 },
 {
  "type": 27,
  "name": "Maior defesa",
  "level": 13,
  "damage": 0,
  "mana": 30,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 28,
  "name": "Maior dano",
  "level": 18,
  "damage": 0,
  "mana": 40,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 30,
  "name": "Invocar Goblin",
  "level": 0,
  "damage": 0,
  "mana": 40,
  "distance": 0,
  "delay": 0,
  "energy": 90,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 31,
  "name": "Invocar Golem de pedra",
  "level": 0,
  "damage": 0,
  "mana": 70,
  "distance": 0,
  "delay": 0,
  "energy": 170,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 32,
  "name": "Invocar Assassino",
  "level": 0,
  "damage": 0,
  "mana": 110,
  "distance": 0,
  "delay": 0,
  "energy": 190,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 33,
  "name": "Invocar Ieti de elite",
  "level": 0,
  "damage": 0,
  "mana": 160,
  "distance": 0,
  "delay": 0,
  "energy": 230,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 34,
  "name": "Invocar Cavaleiro negro",
  "level": 0,
  "damage": 0,
  "mana": 200,
  "distance": 0,
  "delay": 0,
  "energy": 250,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 35,
  "name": "Invocar Bali",
  "level": 0,
  "damage": 0,
  "mana": 250,
  "distance": 0,
  "delay": 0,
  "energy": 260,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 36,
  "name": "Invocar Soldado",
  "level": 0,
  "damage": 0,
  "mana": 350,
  "distance": 0,
  "delay": 0,
  "energy": 280,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 38,
  "name": "Apodrecimento",
  "level": 96,
  "damage": 95,
  "mana": 110,
  "distance": 6,
  "delay": 0,
  "energy": 243,
  "masteryType": 1,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 39,
  "name": "Tempestade de gelo",
  "level": 93,
  "damage": 80,
  "mana": 100,
  "distance": 6,
  "delay": 0,
  "energy": 223,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 40,
  "name": "Nova",
  "level": 100,
  "damage": 0,
  "mana": 180,
  "distance": 6,
  "delay": 0,
  "energy": 258,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 41,
  "name": "Golpe com torção",
  "level": 0,
  "damage": 0,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 42,
  "name": "Golpe raivoso",
  "level": 170,
  "damage": 60,
  "mana": 25,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 4,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 43,
  "name": "Facada da morte",
  "level": 160,
  "damage": 70,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 44,
  "name": "Golpe da lua crescente",
  "level": 0,
  "damage": 90,
  "mana": 22,
  "distance": 4,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 45,
  "name": "Lança",
  "level": 0,
  "damage": 90,
  "mana": 150,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 46,
  "name": "Chuva de estrelas",
  "level": 0,
  "damage": 120,
  "mana": 20,
  "distance": 8,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 47,
  "name": "Empalar",
  "level": 28,
  "damage": 15,
  "mana": 8,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 48,
  "name": "Expandir vida",
  "level": 120,
  "damage": 0,
  "mana": 22,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 49,
  "name": "Sopro de fogo",
  "level": 110,
  "damage": 30,
  "mana": 9,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 50,
  "name": "Chama do mal (Monstro)",
  "level": 60,
  "damage": 120,
  "mana": 160,
  "distance": 0,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 51,
  "name": "Flecha de gelo",
  "level": 0,
  "damage": 105,
  "mana": 10,
  "distance": 8,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 52,
  "name": "Penetração",
  "level": 130,
  "damage": 70,
  "mana": 7,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 55,
  "name": "Golpe de fogo",
  "level": 0,
  "damage": 80,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 56,
  "name": "Golpe poderoso",
  "level": 0,
  "damage": 0,
  "mana": 15,
  "distance": 5,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 57,
  "name": "Golpe em espiral",
  "level": 0,
  "damage": 75,
  "mana": 20,
  "distance": 5,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 60,
  "name": "Força",
  "level": 0,
  "damage": 10,
  "mana": 10,
  "distance": 4,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 61,
  "name": "Explosão de fogo",
  "level": 74,
  "damage": 100,
  "mana": 25,
  "distance": 6,
  "delay": 0,
  "energy": 20,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 62,
  "name": "Terremoto",
  "level": 0,
  "damage": 150,
  "mana": 0,
  "distance": 10,
  "delay": 10000,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 63,
  "name": "Invocar",
  "level": 98,
  "damage": 0,
  "mana": 70,
  "distance": 0,
  "delay": 30000,
  "energy": 34,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 64,
  "name": "Aumentar dano crítico",
  "level": 82,
  "damage": 0,
  "mana": 50,
  "distance": 0,
  "delay": 0,
  "energy": 25,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 65,
  "name": "Ponta elétrica",
  "level": 92,
  "damage": 250,
  "mana": 0,
  "distance": 10,
  "delay": 5000,
  "energy": 29,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 66,
  "name": "Onda de força",
  "level": 0,
  "damage": 50,
  "mana": 10,
  "distance": 4,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 67,
  "name": "Atordoamento",
  "level": 0,
  "damage": 0,
  "mana": 70,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 1,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 68,
  "name": "Cancelar atordoamento",
  "level": 0,
  "damage": 0,
  "mana": 25,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 1,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 69,
  "name": "Expandir mana",
  "level": 0,
  "damage": 0,
  "mana": 35,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 1,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 70,
  "name": "Invisibilidade",
  "level": 0,
  "damage": 0,
  "mana": 80,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 1,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 71,
  "name": "Cancelar invisibilidade",
  "level": 0,
  "damage": 0,
  "mana": 40,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 1,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 72,
  "name": "Abolir magia",
  "level": 0,
  "damage": 0,
  "mana": 90,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 1,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 73,
  "name": "Raios de mana",
  "level": 0,
  "damage": 85,
  "mana": 130,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 74,
  "name": "Explosão de fogo",
  "level": 0,
  "damage": 150,
  "mana": 30,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 76,
  "name": "Tempestade de plasma",
  "level": 110,
  "damage": 60,
  "mana": 50,
  "distance": 6,
  "delay": 1500,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 77,
  "name": "Flecha do infinito",
  "level": 220,
  "damage": 0,
  "mana": 50,
  "distance": 6,
  "delay": 200,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 78,
  "name": "Grito de fogo",
  "level": 102,
  "damage": 130,
  "mana": 45,
  "distance": 6,
  "delay": 0,
  "energy": 32,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 79,
  "name": "Explosão",
  "level": 0,
  "damage": 0,
  "mana": 0,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 200,
  "name": "Invocar monstro",
  "level": 0,
  "damage": 0,
  "mana": 40,
  "distance": 0,
  "delay": 0,
  "energy": 90,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 201,
  "name": "Imunidade a ataque de magia",
  "level": 0,
  "damage": 0,
  "mana": 40,
  "distance": 0,
  "delay": 0,
  "energy": 90,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 202,
  "name": "Imunidade a ataque físico",
  "level": 0,
  "damage": 0,
  "mana": 40,
  "distance": 0,
  "delay": 0,
  "energy": 90,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 203,
  "name": "Poção da bênção",
  "level": 0,
  "damage": 0,
  "mana": 40,
  "distance": 0,
  "delay": 0,
  "energy": 90,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 204,
  "name": "Poção da alma",
  "level": 0,
  "damage": 0,
  "mana": 40,
  "distance": 0,
  "delay": 0,
  "energy": 90,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 210,
  "name": "Magia de proteção",
  "level": 0,
  "damage": 0,
  "mana": 30,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 211,
  "name": "Magia de restrição",
  "level": 0,
  "damage": 0,
  "mana": 30,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 212,
  "name": "Magia da perseguição",
  "level": 0,
  "damage": 0,
  "mana": 30,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 213,
  "name": "Escudo queimado",
  "level": 0,
  "damage": 0,
  "mana": 30,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 214,
  "name": "Drenar vida",
  "level": 35,
  "damage": 35,
  "mana": 50,
  "distance": 6,
  "delay": 0,
  "energy": 93,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 215,
  "name": "Relâmpago em cadeia",
  "level": 75,
  "damage": 70,
  "mana": 85,
  "distance": 6,
  "delay": 0,
  "energy": 75,
  "masteryType": 2,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 217,
  "name": "Reflexo de dano",
  "level": 80,
  "damage": 0,
  "mana": 40,
  "distance": 5,
  "delay": 5000,
  "energy": 111,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 218,
  "name": "Berserker",
  "level": 83,
  "damage": 0,
  "mana": 100,
  "distance": 5,
  "delay": 5000,
  "energy": 181,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 219,
  "name": "Dormir",
  "level": 40,
  "damage": 0,
  "mana": 20,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 2
 },
 {
  "type": 221,
  "name": "Fraqueza",
  "level": 93,
  "damage": 0,
  "mana": 50,
  "distance": 6,
  "delay": 4000,
  "energy": 173,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 222,
  "name": "Inovação",
  "level": 111,
  "damage": 0,
  "mana": 70,
  "distance": 6,
  "delay": 4000,
  "energy": 201,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 223,
  "name": "Explosão",
  "level": 50,
  "damage": 40,
  "mana": 90,
  "distance": 6,
  "delay": 4000,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 224,
  "name": "Requiem",
  "level": 75,
  "damage": 65,
  "mana": 110,
  "distance": 6,
  "delay": 4000,
  "energy": 99,
  "masteryType": 5,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 225,
  "name": "Poluição",
  "level": 85,
  "damage": 80,
  "mana": 120,
  "distance": 6,
  "delay": 4000,
  "energy": 115,
  "masteryType": 2,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 230,
  "name": "Choque de relâmpago",
  "level": 93,
  "damage": 95,
  "mana": 115,
  "distance": 6,
  "delay": 0,
  "energy": 216,
  "masteryType": 2,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 232,
  "name": "Golpe da destruição",
  "level": 100,
  "damage": 110,
  "mana": 30,
  "distance": 5,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 233,
  "name": "Expansão de magia",
  "level": 220,
  "damage": 0,
  "mana": 200,
  "distance": 6,
  "delay": 0,
  "energy": 118,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 234,
  "name": "Recuperação",
  "level": 100,
  "damage": 0,
  "mana": 40,
  "distance": 6,
  "delay": 0,
  "energy": 37,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 1
 },
 {
  "type": 235,
  "name": "Multi-disparo",
  "level": 100,
  "damage": 40,
  "mana": 10,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 236,
  "name": "Ataque de chama",
  "level": 100,
  "damage": 140,
  "mana": 20,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 237,
  "name": "Tempestade gigante",
  "level": 220,
  "damage": 110,
  "mana": 120,
  "distance": 6,
  "delay": 0,
  "energy": 118,
  "masteryType": 5,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 238,
  "name": "Diseier caótico",
  "level": 100,
  "damage": 190,
  "mana": 50,
  "distance": 6,
  "delay": 0,
  "energy": 16,
  "masteryType": 255,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 239,
  "name": "Hab. Autoexplosão Doppeganger",
  "level": 100,
  "damage": 140,
  "mana": 20,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 3,
  "skillUseType": 0,
  "magicIcon": 0,
  "typeSkill": 0
 },
 {
  "type": 300,
  "name": "Aum. Taxa Sucesso do Ataque",
  "level": 1,
  "damage": 400,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 2,
  "typeSkill": 0
 },
 {
  "type": 301,
  "name": "Aum. Taxa Sucesso do Ataque",
  "level": 2,
  "damage": 900,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 2,
  "typeSkill": 0
 },
 {
  "type": 302,
  "name": "Aum. Taxa Sucesso do Ataque",
  "level": 3,
  "damage": 1600,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 2,
  "typeSkill": 0
 },
 {
  "type": 303,
  "name": "Aum. Taxa Sucesso do Ataque",
  "level": 4,
  "damage": 2700,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 2,
  "typeSkill": 0
 },
 {
  "type": 304,
  "name": "Aum. Taxa Sucesso do Ataque",
  "level": 5,
  "damage": 4400,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 2,
  "typeSkill": 0
 },
 {
  "type": 305,
  "name": "Taxa de ataque",
  "level": 1,
  "damage": 1000,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 3,
  "typeSkill": 0
 },
 {
  "type": 306,
  "name": "Taxa de ataque",
  "level": 2,
  "damage": 2300,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 3,
  "typeSkill": 0
 },
 {
  "type": 307,
  "name": "Taxa de ataque",
  "level": 3,
  "damage": 4000,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 3,
  "typeSkill": 0
 },
 {
  "type": 308,
  "name": "Taxa de ataque",
  "level": 4,
  "damage": 6500,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 3,
  "typeSkill": 0
 },
 {
  "type": 309,
  "name": "Taxa de ataque",
  "level": 5,
  "damage": 10000,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 3,
  "typeSkill": 0
 },
 {
  "type": 310,
  "name": "Aum. Taxa de defesa em PvP",
  "level": 1,
  "damage": 600,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 1,
  "typeSkill": 0
 },
 {
  "type": 311,
  "name": "Aum. Taxa de defesa em PvP",
  "level": 2,
  "damage": 1300,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 1,
  "typeSkill": 0
 },
 {
  "type": 312,
  "name": "Aum. Taxa de defesa em PvP",
  "level": 3,
  "damage": 2100,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 1,
  "typeSkill": 0
 },
 {
  "type": 313,
  "name": "Aum. Taxa de defesa em PvP",
  "level": 4,
  "damage": 3000,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 1,
  "typeSkill": 0
 },
 {
  "type": 314,
  "name": "Aum. Taxa de defesa em PvP",
  "level": 5,
  "damage": 4000,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 1,
  "typeSkill": 0
 },
 {
  "type": 315,
  "name": "Redução de duração 1",
  "level": 1,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 4,
  "typeSkill": 0
 },
 {
  "type": 316,
  "name": "Redução de duração 1",
  "level": 2,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 4,
  "typeSkill": 0
 },
 {
  "type": 317,
  "name": "Redução de duração 1",
  "level": 3,
  "damage": 60,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 4,
  "typeSkill": 0
 },
 {
  "type": 318,
  "name": "Redução de duração 1",
  "level": 4,
  "damage": 80,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 4,
  "typeSkill": 0
 },
 {
  "type": 319,
  "name": "Redução de duração 1",
  "level": 5,
  "damage": 100,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 4,
  "typeSkill": 0
 },
 {
  "type": 320,
  "name": "Redução de duração 2",
  "level": 1,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 5,
  "typeSkill": 0
 },
 {
  "type": 321,
  "name": "Redução de duração 2",
  "level": 2,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 5,
  "typeSkill": 0
 },
 {
  "type": 322,
  "name": "Redução de duração 2",
  "level": 3,
  "damage": 60,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 5,
  "typeSkill": 0
 },
 {
  "type": 323,
  "name": "Redução de duração 2",
  "level": 4,
  "damage": 80,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 5,
  "typeSkill": 0
 },
 {
  "type": 324,
  "name": "Redução de duração 2",
  "level": 5,
  "damage": 100,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 5,
  "typeSkill": 0
 },
 {
  "type": 325,
  "name": "Aum. da Resistência (veneno)",
  "level": 1,
  "damage": 1,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 3,
  "magicIcon": 6,
  "typeSkill": 0
 },
 {
  "type": 326,
  "name": "Aum. da Resistência (veneno)",
  "level": 2,
  "damage": 2,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 3,
  "magicIcon": 6,
  "typeSkill": 0
 },
 {
  "type": 327,
  "name": "Aum. da Resistência (veneno)",
  "level": 3,
  "damage": 3,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 3,
  "magicIcon": 6,
  "typeSkill": 0
 },
 {
  "type": 328,
  "name": "Aum. da Resistência (veneno)",
  "level": 4,
  "damage": 4,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 3,
  "magicIcon": 6,
  "typeSkill": 0
 },
 {
  "type": 329,
  "name": "Aum. da Resistência (veneno)",
  "level": 5,
  "damage": 5,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 3,
  "magicIcon": 6,
  "typeSkill": 0
 },
 {
  "type": 330,
  "name": "Aumento da resistência (raio)",
  "level": 1,
  "damage": 1,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 3,
  "magicIcon": 7,
  "typeSkill": 0
 },
 {
  "type": 331,
  "name": "Aumento da resistência (raio)",
  "level": 2,
  "damage": 2,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 3,
  "magicIcon": 7,
  "typeSkill": 0
 },
 {
  "type": 332,
  "name": "Aumento da resistência (raio)",
  "level": 3,
  "damage": 3,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 3,
  "magicIcon": 7,
  "typeSkill": 0
 },
 {
  "type": 333,
  "name": "Aumento da resistência (raio)",
  "level": 4,
  "damage": 4,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 3,
  "magicIcon": 7,
  "typeSkill": 0
 },
 {
  "type": 334,
  "name": "Aumento da resistência (raio)",
  "level": 5,
  "damage": 5,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 3,
  "magicIcon": 7,
  "typeSkill": 0
 },
 {
  "type": 335,
  "name": "Aumento da resistência (gelo)",
  "level": 1,
  "damage": 1,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 3,
  "magicIcon": 8,
  "typeSkill": 0
 },
 {
  "type": 336,
  "name": "Aumento da resistência (gelo)",
  "level": 2,
  "damage": 2,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 3,
  "magicIcon": 8,
  "typeSkill": 0
 },
 {
  "type": 337,
  "name": "Aumento da resistência (gelo)",
  "level": 3,
  "damage": 3,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 3,
  "magicIcon": 8,
  "typeSkill": 0
 },
 {
  "type": 338,
  "name": "Aumento da resistência (gelo)",
  "level": 4,
  "damage": 4,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 3,
  "magicIcon": 8,
  "typeSkill": 0
 },
 {
  "type": 339,
  "name": "Aumento da resistência (gelo)",
  "level": 5,
  "damage": 5,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 0,
  "skillUseType": 3,
  "magicIcon": 8,
  "typeSkill": 0
 },
 {
  "type": 340,
  "name": "Incremento automático de HP",
  "level": 1,
  "damage": 1,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 9,
  "typeSkill": 0
 },
 {
  "type": 341,
  "name": "Incremento automático de HP",
  "level": 2,
  "damage": 2,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 9,
  "typeSkill": 0
 },
 {
  "type": 342,
  "name": "Incremento automático de HP",
  "level": 3,
  "damage": 3,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 9,
  "typeSkill": 0
 },
 {
  "type": 343,
  "name": "Incremento automático de HP",
  "level": 4,
  "damage": 4,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 9,
  "typeSkill": 0
 },
 {
  "type": 344,
  "name": "Incremento automático de HP",
  "level": 5,
  "damage": 5,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 9,
  "typeSkill": 0
 },
 {
  "type": 345,
  "name": "Aumento de Zen",
  "level": 1,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 10,
  "typeSkill": 0
 },
 {
  "type": 346,
  "name": "Aumento de Zen",
  "level": 2,
  "damage": 80,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 10,
  "typeSkill": 0
 },
 {
  "type": 347,
  "name": "Aumento de Zen",
  "level": 3,
  "damage": 120,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 10,
  "typeSkill": 0
 },
 {
  "type": 348,
  "name": "Aumento de Zen",
  "level": 4,
  "damage": 160,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 10,
  "typeSkill": 0
 },
 {
  "type": 349,
  "name": "Aumento de Zen",
  "level": 5,
  "damage": 200,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 10,
  "typeSkill": 0
 },
 {
  "type": 350,
  "name": "Aumento da defesa",
  "level": 1,
  "damage": 50,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 11,
  "typeSkill": 0
 },
 {
  "type": 351,
  "name": "Aumento da defesa",
  "level": 2,
  "damage": 100,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 11,
  "typeSkill": 0
 },
 {
  "type": 352,
  "name": "Aumento da defesa",
  "level": 3,
  "damage": 150,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 11,
  "typeSkill": 0
 },
 {
  "type": 353,
  "name": "Aumento da defesa",
  "level": 4,
  "damage": 200,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 11,
  "typeSkill": 0
 },
 {
  "type": 354,
  "name": "Aumento da defesa",
  "level": 5,
  "damage": 250,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 11,
  "typeSkill": 0
 },
 {
  "type": 355,
  "name": "Aumento da vida máxima",
  "level": 1,
  "damage": 50,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 12,
  "typeSkill": 0
 },
 {
  "type": 356,
  "name": "Aumento da vida máxima",
  "level": 2,
  "damage": 100,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 12,
  "typeSkill": 0
 },
 {
  "type": 357,
  "name": "Aumento da vida máxima",
  "level": 3,
  "damage": 150,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 12,
  "typeSkill": 0
 },
 {
  "type": 358,
  "name": "Aumento da vida máxima",
  "level": 4,
  "damage": 200,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 12,
  "typeSkill": 0
 },
 {
  "type": 359,
  "name": "Aumento da vida máxima",
  "level": 5,
  "damage": 300,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 12,
  "typeSkill": 0
 },
 {
  "type": 360,
  "name": "Aumento de AG máxima",
  "level": 1,
  "damage": 60,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 13,
  "typeSkill": 0
 },
 {
  "type": 361,
  "name": "Aumento de AG máxima",
  "level": 2,
  "damage": 120,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 13,
  "typeSkill": 0
 },
 {
  "type": 362,
  "name": "Aumento de AG máxima",
  "level": 3,
  "damage": 180,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 13,
  "typeSkill": 0
 },
 {
  "type": 363,
  "name": "Aumento de AG máxima",
  "level": 4,
  "damage": 240,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 13,
  "typeSkill": 0
 },
 {
  "type": 364,
  "name": "Aumento de AG máxima",
  "level": 5,
  "damage": 300,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 13,
  "typeSkill": 0
 },
 {
  "type": 365,
  "name": "Increm. Mana com At. Monstro",
  "level": 1,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 14,
  "typeSkill": 0
 },
 {
  "type": 366,
  "name": "Increm. Mana com At. Monstro",
  "level": 2,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 14,
  "typeSkill": 0
 },
 {
  "type": 367,
  "name": "Increm. Mana com At. Monstro",
  "level": 3,
  "damage": 14,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 14,
  "typeSkill": 0
 },
 {
  "type": 368,
  "name": "Increm. Mana com At. Monstro",
  "level": 4,
  "damage": 10,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 14,
  "typeSkill": 0
 },
 {
  "type": 369,
  "name": "Increm. Mana com At. Monstro",
  "level": 5,
  "damage": 8,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 14,
  "typeSkill": 0
 },
 {
  "type": 370,
  "name": "Increm. Vida com At. Monstro",
  "level": 1,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 15,
  "typeSkill": 0
 },
 {
  "type": 371,
  "name": "Increm. Vida com At. Monstro",
  "level": 2,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 15,
  "typeSkill": 0
 },
 {
  "type": 372,
  "name": "Increm. Vida com At. Monstro",
  "level": 3,
  "damage": 14,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 15,
  "typeSkill": 0
 },
 {
  "type": 373,
  "name": "Increm. Vida com At. Monstro",
  "level": 4,
  "damage": 10,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 15,
  "typeSkill": 0
 },
 {
  "type": 374,
  "name": "Increm. Vida com At. Monstro",
  "level": 5,
  "damage": 8,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 15,
  "typeSkill": 0
 },
 {
  "type": 375,
  "name": "Increm. SD com At. Monstro",
  "level": 1,
  "damage": 7,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 16,
  "typeSkill": 0
 },
 {
  "type": 376,
  "name": "Increm. SD com At. Monstro",
  "level": 2,
  "damage": 6,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 16,
  "typeSkill": 0
 },
 {
  "type": 377,
  "name": "Increm. SD com At. Monstro",
  "level": 3,
  "damage": 5,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 16,
  "typeSkill": 0
 },
 {
  "type": 378,
  "name": "Increm. SD com At. Monstro",
  "level": 4,
  "damage": 4,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 16,
  "typeSkill": 0
 },
 {
  "type": 379,
  "name": "Increm. SD com At. Monstro",
  "level": 5,
  "damage": 3,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 16,
  "typeSkill": 0
 },
 {
  "type": 380,
  "name": "Aumento de EXP",
  "level": 1,
  "damage": 8,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 17,
  "typeSkill": 0
 },
 {
  "type": 381,
  "name": "Aumento de EXP",
  "level": 2,
  "damage": 16,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 17,
  "typeSkill": 0
 },
 {
  "type": 382,
  "name": "Aumento de EXP",
  "level": 3,
  "damage": 24,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 17,
  "typeSkill": 0
 },
 {
  "type": 383,
  "name": "Aumento de EXP",
  "level": 4,
  "damage": 32,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 17,
  "typeSkill": 0
 },
 {
  "type": 384,
  "name": "Aumento de EXP",
  "level": 5,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 17,
  "typeSkill": 0
 },
 {
  "type": 385,
  "name": "Aumento de SD máxima",
  "level": 1,
  "damage": 300,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 18,
  "typeSkill": 0
 },
 {
  "type": 386,
  "name": "Aumento de SD máxima",
  "level": 2,
  "damage": 450,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 18,
  "typeSkill": 0
 },
 {
  "type": 387,
  "name": "Aumento de SD máxima",
  "level": 3,
  "damage": 600,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 18,
  "typeSkill": 0
 },
 {
  "type": 388,
  "name": "Aumento de SD máxima",
  "level": 4,
  "damage": 750,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 18,
  "typeSkill": 0
 },
 {
  "type": 389,
  "name": "Aumento de SD máxima",
  "level": 5,
  "damage": 900,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 18,
  "typeSkill": 0
 },
 {
  "type": 390,
  "name": "Aum. Vel. Recuperação de SD",
  "level": 1,
  "damage": 10,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 19,
  "typeSkill": 0
 },
 {
  "type": 391,
  "name": "Aum. Vel. Recuperação de SD",
  "level": 2,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 19,
  "typeSkill": 0
 },
 {
  "type": 392,
  "name": "Aum. Vel. Recuperação de SD",
  "level": 3,
  "damage": 30,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 19,
  "typeSkill": 0
 },
 {
  "type": 393,
  "name": "Aum. Vel. Recuperação de SD",
  "level": 4,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 19,
  "typeSkill": 0
 },
 {
  "type": 394,
  "name": "Aum. Vel. Recuperação de SD",
  "level": 5,
  "damage": 50,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 19,
  "typeSkill": 0
 },
 {
  "type": 395,
  "name": "Aum. Poder de Ataque Máximo",
  "level": 1,
  "damage": 10,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 20,
  "typeSkill": 0
 },
 {
  "type": 396,
  "name": "Aum. Poder de Ataque Máximo",
  "level": 2,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 20,
  "typeSkill": 0
 },
 {
  "type": 397,
  "name": "Aum. Poder de Ataque Máximo",
  "level": 3,
  "damage": 30,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 20,
  "typeSkill": 0
 },
 {
  "type": 398,
  "name": "Aum. Poder de Ataque Máximo",
  "level": 4,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 20,
  "typeSkill": 0
 },
 {
  "type": 399,
  "name": "Aum. Poder de Ataque Máximo",
  "level": 5,
  "damage": 50,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 20,
  "typeSkill": 0
 },
 {
  "type": 400,
  "name": "Aum. Poder de Ataque Mínimo",
  "level": 1,
  "damage": 8,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 21,
  "typeSkill": 0
 },
 {
  "type": 401,
  "name": "Aum. Poder de Ataque Mínimo",
  "level": 2,
  "damage": 16,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 21,
  "typeSkill": 0
 },
 {
  "type": 402,
  "name": "Aum. Poder de Ataque Mínimo",
  "level": 3,
  "damage": 24,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 21,
  "typeSkill": 0
 },
 {
  "type": 403,
  "name": "Aum. Poder de Ataque Mínimo",
  "level": 4,
  "damage": 32,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 21,
  "typeSkill": 0
 },
 {
  "type": 404,
  "name": "Aum. Poder de Ataque Mínimo",
  "level": 5,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 21,
  "typeSkill": 0
 },
 {
  "type": 405,
  "name": "Reforço de redução de mana",
  "level": 1,
  "damage": 5,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 22,
  "typeSkill": 0
 },
 {
  "type": 406,
  "name": "Reforço de redução de mana",
  "level": 2,
  "damage": 10,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 22,
  "typeSkill": 0
 },
 {
  "type": 407,
  "name": "Reforço de redução de mana",
  "level": 3,
  "damage": 15,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 22,
  "typeSkill": 0
 },
 {
  "type": 408,
  "name": "Reforço de redução de mana",
  "level": 4,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 22,
  "typeSkill": 0
 },
 {
  "type": 409,
  "name": "Reforço de redução de mana",
  "level": 5,
  "damage": 25,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 22,
  "typeSkill": 0
 },
 {
  "type": 410,
  "name": "Aumento de magia máxima",
  "level": 1,
  "damage": 10,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 411,
  "name": "Aumento de magia máxima",
  "level": 2,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 412,
  "name": "Aumento de magia máxima",
  "level": 3,
  "damage": 30,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 413,
  "name": "Aumento de magia máxima",
  "level": 4,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 414,
  "name": "Aumento de magia máxima",
  "level": 5,
  "damage": 50,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 415,
  "name": "Aumento de magia mínima",
  "level": 1,
  "damage": 8,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 416,
  "name": "Aumento de magia mínima",
  "level": 2,
  "damage": 16,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 417,
  "name": "Aumento de magia mínima",
  "level": 3,
  "damage": 24,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 418,
  "name": "Aumento de magia mínima",
  "level": 4,
  "damage": 32,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 419,
  "name": "Aumento de magia mínima",
  "level": 5,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 420,
  "name": "Aum Duração Disp. Animal Est.",
  "level": 1,
  "damage": 100,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 25,
  "typeSkill": 0
 },
 {
  "type": 421,
  "name": "Aum Duração Disp. Animal Est.",
  "level": 2,
  "damage": 200,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 25,
  "typeSkill": 0
 },
 {
  "type": 422,
  "name": "Aum Duração Disp. Animal Est.",
  "level": 3,
  "damage": 300,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 25,
  "typeSkill": 0
 },
 {
  "type": 423,
  "name": "Aum Duração Disp. Animal Est.",
  "level": 4,
  "damage": 400,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 25,
  "typeSkill": 0
 },
 {
  "type": 424,
  "name": "Aum Duração Disp. Animal Est.",
  "level": 5,
  "damage": 500,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 25,
  "typeSkill": 0
 },
 {
  "type": 425,
  "name": "Aum. Dano Máximo Poder/Magia",
  "level": 1,
  "damage": 10,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 426,
  "name": "Aum. Dano Máximo Poder/Magia",
  "level": 2,
  "damage": 20,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 427,
  "name": "Aum. Dano Máximo Poder/Magia",
  "level": 3,
  "damage": 30,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 428,
  "name": "Aum. Dano Máximo Poder/Magia",
  "level": 4,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 429,
  "name": "Aum. Dano Máximo Poder/Magia",
  "level": 5,
  "damage": 50,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 23,
  "typeSkill": 0
 },
 {
  "type": 430,
  "name": "Aum. Dano Mínimo Poder/Magia",
  "level": 1,
  "damage": 8,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 431,
  "name": "Aum. Dano Mínimo Poder/Magia",
  "level": 2,
  "damage": 16,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 432,
  "name": "Aum. Dano Mínimo Poder/Magia",
  "level": 3,
  "damage": 24,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 433,
  "name": "Aum. Dano Mínimo Poder/Magia",
  "level": 4,
  "damage": 32,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 434,
  "name": "Aum. Dano Mínimo Poder/Magia",
  "level": 5,
  "damage": 40,
  "mana": 0,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 3,
  "magicIcon": 24,
  "typeSkill": 0
 },
 {
  "type": 435,
  "name": "Reforço de Barreira da alma",
  "level": 1,
  "damage": 3,
  "mana": 77,
  "distance": 6,
  "delay": 0,
  "energy": 126,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 28,
  "typeSkill": 1
 },
 {
  "type": 436,
  "name": "Reforço de Barreira da alma",
  "level": 2,
  "damage": 6,
  "mana": 84,
  "distance": 6,
  "delay": 0,
  "energy": 126,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 28,
  "typeSkill": 1
 },
 {
  "type": 437,
  "name": "Reforço de Barreira da alma",
  "level": 3,
  "damage": 9,
  "mana": 91,
  "distance": 6,
  "delay": 0,
  "energy": 126,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 28,
  "typeSkill": 1
 },
 {
  "type": 438,
  "name": "Reforço de Barreira da alma",
  "level": 4,
  "damage": 12,
  "mana": 98,
  "distance": 6,
  "delay": 0,
  "energy": 126,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 28,
  "typeSkill": 1
 },
 {
  "type": 439,
  "name": "Reforço de Barreira da alma",
  "level": 5,
  "damage": 15,
  "mana": 105,
  "distance": 6,
  "delay": 0,
  "energy": 126,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 28,
  "typeSkill": 1
 },
 {
  "type": 440,
  "name": "Reforço de Fogo do inferno",
  "level": 1,
  "damage": 135,
  "mana": 176,
  "distance": 0,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 29,
  "typeSkill": 0
 },
 {
  "type": 441,
  "name": "Reforço de Fogo do inferno",
  "level": 2,
  "damage": 150,
  "mana": 192,
  "distance": 0,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 29,
  "typeSkill": 0
 },
 {
  "type": 442,
  "name": "Reforço de Fogo do inferno",
  "level": 3,
  "damage": 165,
  "mana": 208,
  "distance": 0,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 29,
  "typeSkill": 0
 },
 {
  "type": 443,
  "name": "Reforço de Fogo do inferno",
  "level": 4,
  "damage": 180,
  "mana": 224,
  "distance": 0,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 29,
  "typeSkill": 0
 },
 {
  "type": 444,
  "name": "Reforço de Fogo do inferno",
  "level": 5,
  "damage": 195,
  "mana": 240,
  "distance": 0,
  "delay": 0,
  "energy": 100,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 29,
  "typeSkill": 0
 },
 {
  "type": 445,
  "name": "Reforço de Espírito maligno",
  "level": 1,
  "damage": 50,
  "mana": 99,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 446,
  "name": "Reforço de Espírito maligno",
  "level": 2,
  "damage": 55,
  "mana": 108,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 447,
  "name": "Reforço de Espírito maligno",
  "level": 3,
  "damage": 60,
  "mana": 117,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 448,
  "name": "Reforço de Espírito maligno",
  "level": 4,
  "damage": 65,
  "mana": 126,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 449,
  "name": "Reforço de Espírito maligno",
  "level": 5,
  "damage": 70,
  "mana": 135,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 450,
  "name": "Reforço de Gelo súbito",
  "level": 1,
  "damage": 85,
  "mana": 110,
  "distance": 6,
  "delay": 0,
  "energy": 223,
  "masteryType": 0,
  "skillUseType": 4,
  "magicIcon": 31,
  "typeSkill": 0
 },
 {
  "type": 451,
  "name": "Reforço de Gelo súbito",
  "level": 2,
  "damage": 90,
  "mana": 120,
  "distance": 6,
  "delay": 0,
  "energy": 223,
  "masteryType": 0,
  "skillUseType": 4,
  "magicIcon": 31,
  "typeSkill": 0
 },
 {
  "type": 452,
  "name": "Reforço de Gelo súbito",
  "level": 3,
  "damage": 95,
  "mana": 130,
  "distance": 6,
  "delay": 0,
  "energy": 223,
  "masteryType": 0,
  "skillUseType": 4,
  "magicIcon": 31,
  "typeSkill": 0
 },
 {
  "type": 453,
  "name": "Reforço de Gelo súbito",
  "level": 4,
  "damage": 100,
  "mana": 140,
  "distance": 6,
  "delay": 0,
  "energy": 223,
  "masteryType": 0,
  "skillUseType": 4,
  "magicIcon": 31,
  "typeSkill": 0
 },
 {
  "type": 454,
  "name": "Reforço de Gelo súbito",
  "level": 5,
  "damage": 105,
  "mana": 150,
  "distance": 6,
  "delay": 0,
  "energy": 223,
  "masteryType": 0,
  "skillUseType": 4,
  "magicIcon": 31,
  "typeSkill": 0
 },
 {
  "type": 455,
  "name": "Reforço de Golpe com torção",
  "level": 1,
  "damage": 2,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 32,
  "typeSkill": 0
 },
 {
  "type": 456,
  "name": "Reforço de Golpe com torção",
  "level": 2,
  "damage": 4,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 32,
  "typeSkill": 0
 },
 {
  "type": 457,
  "name": "Reforço de Golpe com torção",
  "level": 3,
  "damage": 6,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 32,
  "typeSkill": 0
 },
 {
  "type": 458,
  "name": "Reforço de Golpe com torção",
  "level": 4,
  "damage": 8,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 32,
  "typeSkill": 0
 },
 {
  "type": 459,
  "name": "Reforço de Golpe com torção",
  "level": 5,
  "damage": 10,
  "mana": 10,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 32,
  "typeSkill": 0
 },
 {
  "type": 460,
  "name": "Reforço de Golpe",
  "level": 1,
  "damage": 75,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 33,
  "typeSkill": 0
 },
 {
  "type": 461,
  "name": "Reforço de Golpe",
  "level": 2,
  "damage": 80,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 33,
  "typeSkill": 0
 },
 {
  "type": 462,
  "name": "Reforço de Golpe",
  "level": 3,
  "damage": 85,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 33,
  "typeSkill": 0
 },
 {
  "type": 463,
  "name": "Reforço de Golpe",
  "level": 4,
  "damage": 90,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 33,
  "typeSkill": 0
 },
 {
  "type": 464,
  "name": "Reforço de Golpe",
  "level": 5,
  "damage": 95,
  "mana": 15,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 33,
  "typeSkill": 0
 },
 {
  "type": 465,
  "name": "Reforço de Golpe raivoso",
  "level": 1,
  "damage": 65,
  "mana": 25,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 4,
  "skillUseType": 4,
  "magicIcon": 34,
  "typeSkill": 0
 },
 {
  "type": 466,
  "name": "Reforço de Golpe raivoso",
  "level": 2,
  "damage": 70,
  "mana": 25,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 4,
  "skillUseType": 4,
  "magicIcon": 34,
  "typeSkill": 0
 },
 {
  "type": 467,
  "name": "Reforço de Golpe raivoso",
  "level": 3,
  "damage": 75,
  "mana": 25,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 4,
  "skillUseType": 4,
  "magicIcon": 34,
  "typeSkill": 0
 },
 {
  "type": 468,
  "name": "Reforço de Golpe raivoso",
  "level": 4,
  "damage": 80,
  "mana": 25,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 4,
  "skillUseType": 4,
  "magicIcon": 34,
  "typeSkill": 0
 },
 {
  "type": 469,
  "name": "Reforço de Golpe raivoso",
  "level": 5,
  "damage": 85,
  "mana": 25,
  "distance": 4,
  "delay": 0,
  "energy": 0,
  "masteryType": 4,
  "skillUseType": 4,
  "magicIcon": 34,
  "typeSkill": 0
 },
 {
  "type": 470,
  "name": "Reforço de Expandir vida",
  "level": 1,
  "damage": 2,
  "mana": 22,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 35,
  "typeSkill": 1
 },
 {
  "type": 471,
  "name": "Reforço de Expandir vida",
  "level": 2,
  "damage": 4,
  "mana": 22,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 35,
  "typeSkill": 1
 },
 {
  "type": 472,
  "name": "Reforço de Expandir vida",
  "level": 3,
  "damage": 6,
  "mana": 22,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 35,
  "typeSkill": 1
 },
 {
  "type": 473,
  "name": "Reforço de Expandir vida",
  "level": 4,
  "damage": 8,
  "mana": 22,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 35,
  "typeSkill": 1
 },
 {
  "type": 474,
  "name": "Reforço de Expandir vida",
  "level": 5,
  "damage": 10,
  "mana": 22,
  "distance": 0,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 35,
  "typeSkill": 1
 },
 {
  "type": 475,
  "name": "Reforço de Cura",
  "level": 1,
  "damage": 10,
  "mana": 22,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 36,
  "typeSkill": 3
 },
 {
  "type": 476,
  "name": "Reforço de Cura",
  "level": 2,
  "damage": 20,
  "mana": 24,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 36,
  "typeSkill": 3
 },
 {
  "type": 477,
  "name": "Reforço de Cura",
  "level": 3,
  "damage": 30,
  "mana": 26,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 36,
  "typeSkill": 3
 },
 {
  "type": 478,
  "name": "Reforço de Cura",
  "level": 4,
  "damage": 40,
  "mana": 28,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 36,
  "typeSkill": 3
 },
 {
  "type": 479,
  "name": "Reforço de Cura",
  "level": 5,
  "damage": 50,
  "mana": 30,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 36,
  "typeSkill": 3
 },
 {
  "type": 480,
  "name": "Reforço de Maior defesa",
  "level": 1,
  "damage": 76,
  "mana": 33,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 37,
  "typeSkill": 1
 },
 {
  "type": 481,
  "name": "Reforço de Maior defesa",
  "level": 2,
  "damage": 72,
  "mana": 36,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 37,
  "typeSkill": 1
 },
 {
  "type": 482,
  "name": "Reforço de Maior defesa",
  "level": 3,
  "damage": 68,
  "mana": 39,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 37,
  "typeSkill": 1
 },
 {
  "type": 483,
  "name": "Reforço de Maior defesa",
  "level": 4,
  "damage": 64,
  "mana": 42,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 37,
  "typeSkill": 1
 },
 {
  "type": 484,
  "name": "Reforço de Maior defesa",
  "level": 5,
  "damage": 60,
  "mana": 45,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 37,
  "typeSkill": 1
 },
 {
  "type": 485,
  "name": "Reforço de Maior dano",
  "level": 1,
  "damage": 67,
  "mana": 44,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 38,
  "typeSkill": 1
 },
 {
  "type": 486,
  "name": "Reforço de Maior dano",
  "level": 2,
  "damage": 62,
  "mana": 48,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 38,
  "typeSkill": 1
 },
 {
  "type": 487,
  "name": "Reforço de Maior dano",
  "level": 3,
  "damage": 59,
  "mana": 52,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 38,
  "typeSkill": 1
 },
 {
  "type": 488,
  "name": "Reforço de Maior dano",
  "level": 4,
  "damage": 56,
  "mana": 56,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 38,
  "typeSkill": 1
 },
 {
  "type": 489,
  "name": "Reforço de Maior dano",
  "level": 5,
  "damage": 53,
  "mana": 60,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 38,
  "typeSkill": 1
 },
 {
  "type": 490,
  "name": "Reforço de Tiro triplo",
  "level": 1,
  "damage": 2,
  "mana": 5,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 39,
  "typeSkill": 0
 },
 {
  "type": 491,
  "name": "Reforço de Tiro triplo",
  "level": 2,
  "damage": 4,
  "mana": 5,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 39,
  "typeSkill": 0
 },
 {
  "type": 492,
  "name": "Reforço de Tiro triplo",
  "level": 3,
  "damage": 6,
  "mana": 5,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 39,
  "typeSkill": 0
 },
 {
  "type": 493,
  "name": "Reforço de Tiro triplo",
  "level": 4,
  "damage": 8,
  "mana": 5,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 39,
  "typeSkill": 0
 },
 {
  "type": 494,
  "name": "Reforço de Tiro triplo",
  "level": 5,
  "damage": 10,
  "mana": 5,
  "distance": 6,
  "delay": 0,
  "energy": 0,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 39,
  "typeSkill": 0
 },
 {
  "type": 495,
  "name": "Reforço de Golpe com torção",
  "level": 1,
  "damage": 2,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 40,
  "typeSkill": 0
 },
 {
  "type": 496,
  "name": "Reforço de Golpe com torção",
  "level": 2,
  "damage": 4,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 40,
  "typeSkill": 0
 },
 {
  "type": 497,
  "name": "Reforço de Golpe com torção",
  "level": 3,
  "damage": 6,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 40,
  "typeSkill": 0
 },
 {
  "type": 498,
  "name": "Reforço de Golpe com torção",
  "level": 4,
  "damage": 8,
  "mana": 10,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 40,
  "typeSkill": 0
 },
 {
  "type": 499,
  "name": "Reforço de Golpe com torção",
  "level": 5,
  "damage": 10,
  "mana": 10,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 5,
  "skillUseType": 4,
  "magicIcon": 40,
  "typeSkill": 0
 },
 {
  "type": 500,
  "name": "Reforço de Ataque sanguinário",
  "level": 1,
  "damage": 85,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 4,
  "magicIcon": 41,
  "typeSkill": 2
 },
 {
  "type": 501,
  "name": "Reforço de Ataque sanguinário",
  "level": 2,
  "damage": 90,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 4,
  "magicIcon": 41,
  "typeSkill": 2
 },
 {
  "type": 502,
  "name": "Reforço de Ataque sanguinário",
  "level": 3,
  "damage": 95,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 4,
  "magicIcon": 41,
  "typeSkill": 2
 },
 {
  "type": 503,
  "name": "Reforço de Ataque sanguinário",
  "level": 4,
  "damage": 100,
  "mana": 15,
  "distance": 2,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 4,
  "magicIcon": 41,
  "typeSkill": 2
 },
 {
  "type": 504,
  "name": "Reforço de Ataque sanguinário",
  "level": 5,
  "damage": 105,
  "mana": 15,
  "distance": 3,
  "delay": 0,
  "energy": 0,
  "masteryType": 1,
  "skillUseType": 4,
  "magicIcon": 41,
  "typeSkill": 2
 },
 {
  "type": 505,
  "name": "Reforço de Golpe poderoso",
  "level": 1,
  "damage": 5,
  "mana": 15,
  "distance": 5,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 42,
  "typeSkill": 0
 },
 {
  "type": 506,
  "name": "Reforço de Golpe poderoso",
  "level": 2,
  "damage": 10,
  "mana": 15,
  "distance": 5,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 42,
  "typeSkill": 0
 },
 {
  "type": 507,
  "name": "Reforço de Golpe poderoso",
  "level": 3,
  "damage": 15,
  "mana": 15,
  "distance": 5,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 42,
  "typeSkill": 0
 },
 {
  "type": 508,
  "name": "Reforço de Golpe poderoso",
  "level": 4,
  "damage": 20,
  "mana": 15,
  "distance": 5,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 42,
  "typeSkill": 0
 },
 {
  "type": 509,
  "name": "Reforço de Golpe poderoso",
  "level": 5,
  "damage": 25,
  "mana": 15,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 42,
  "typeSkill": 0
 },
 {
  "type": 510,
  "name": "Reforço de Explosão",
  "level": 1,
  "damage": 80,
  "mana": 165,
  "distance": 3,
  "delay": 0,
  "energy": 150,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 43,
  "typeSkill": 0
 },
 {
  "type": 511,
  "name": "Reforço de Explosão",
  "level": 2,
  "damage": 90,
  "mana": 180,
  "distance": 3,
  "delay": 0,
  "energy": 150,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 43,
  "typeSkill": 0
 },
 {
  "type": 512,
  "name": "Reforço de Explosão",
  "level": 3,
  "damage": 100,
  "mana": 195,
  "distance": 3,
  "delay": 0,
  "energy": 150,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 43,
  "typeSkill": 0
 },
 {
  "type": 513,
  "name": "Reforço de Explosão",
  "level": 4,
  "damage": 110,
  "mana": 210,
  "distance": 3,
  "delay": 0,
  "energy": 150,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 43,
  "typeSkill": 0
 },
 {
  "type": 514,
  "name": "Reforço de Explosão",
  "level": 5,
  "damage": 120,
  "mana": 225,
  "distance": 4,
  "delay": 0,
  "energy": 150,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 43,
  "typeSkill": 0
 },
 {
  "type": 515,
  "name": "Reforço de Terremoto",
  "level": 1,
  "damage": 155,
  "mana": 0,
  "distance": 10,
  "delay": 10000,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 44,
  "typeSkill": 0
 },
 {
  "type": 516,
  "name": "Reforço de Terremoto",
  "level": 2,
  "damage": 160,
  "mana": 0,
  "distance": 10,
  "delay": 10000,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 44,
  "typeSkill": 0
 },
 {
  "type": 517,
  "name": "Reforço de Terremoto",
  "level": 3,
  "damage": 165,
  "mana": 0,
  "distance": 10,
  "delay": 10000,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 44,
  "typeSkill": 0
 },
 {
  "type": 518,
  "name": "Reforço de Terremoto",
  "level": 4,
  "damage": 170,
  "mana": 0,
  "distance": 10,
  "delay": 10000,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 44,
  "typeSkill": 0
 },
 {
  "type": 519,
  "name": "Reforço de Terremoto",
  "level": 5,
  "damage": 175,
  "mana": 0,
  "distance": 10,
  "delay": 10000,
  "energy": 0,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 44,
  "typeSkill": 0
 },
 {
  "type": 520,
  "name": "reforço de Explosão de fogo",
  "level": 1,
  "damage": 105,
  "mana": 25,
  "distance": 6,
  "delay": 0,
  "energy": 20,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 45,
  "typeSkill": 0
 },
 {
  "type": 521,
  "name": "reforço de Explosão de fogo",
  "level": 2,
  "damage": 110,
  "mana": 25,
  "distance": 6,
  "delay": 0,
  "energy": 20,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 45,
  "typeSkill": 0
 },
 {
  "type": 522,
  "name": "reforço de Explosão de fogo",
  "level": 3,
  "damage": 115,
  "mana": 25,
  "distance": 6,
  "delay": 0,
  "energy": 20,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 45,
  "typeSkill": 0
 },
 {
  "type": 523,
  "name": "reforço de Explosão de fogo",
  "level": 4,
  "damage": 120,
  "mana": 25,
  "distance": 6,
  "delay": 0,
  "energy": 20,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 45,
  "typeSkill": 0
 },
 {
  "type": 524,
  "name": "reforço de Explosão de fogo",
  "level": 5,
  "damage": 125,
  "mana": 25,
  "distance": 6,
  "delay": 0,
  "energy": 20,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 45,
  "typeSkill": 0
 },
 {
  "type": 525,
  "name": "Reforço de Grito de fogo",
  "level": 1,
  "damage": 135,
  "mana": 45,
  "distance": 6,
  "delay": 0,
  "energy": 32,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 46,
  "typeSkill": 0
 },
 {
  "type": 526,
  "name": "Reforço de Grito de fogo",
  "level": 2,
  "damage": 140,
  "mana": 45,
  "distance": 6,
  "delay": 0,
  "energy": 32,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 46,
  "typeSkill": 0
 },
 {
  "type": 527,
  "name": "Reforço de Grito de fogo",
  "level": 3,
  "damage": 145,
  "mana": 45,
  "distance": 6,
  "delay": 0,
  "energy": 32,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 46,
  "typeSkill": 0
 },
 {
  "type": 528,
  "name": "Reforço de Grito de fogo",
  "level": 4,
  "damage": 150,
  "mana": 45,
  "distance": 6,
  "delay": 0,
  "energy": 32,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 46,
  "typeSkill": 0
 },
 {
  "type": 529,
  "name": "Reforço de Grito de fogo",
  "level": 5,
  "damage": 155,
  "mana": 45,
  "distance": 6,
  "delay": 0,
  "energy": 32,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 46,
  "typeSkill": 0
 },
 {
  "type": 530,
  "name": "Reforço de Espírito maligno",
  "level": 1,
  "damage": 50,
  "mana": 99,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 531,
  "name": "Reforço de Espírito maligno",
  "level": 2,
  "damage": 55,
  "mana": 108,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 532,
  "name": "Reforço de Espírito maligno",
  "level": 3,
  "damage": 60,
  "mana": 117,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 533,
  "name": "Reforço de Espírito maligno",
  "level": 4,
  "damage": 65,
  "mana": 126,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 534,
  "name": "Reforço de Espírito maligno",
  "level": 5,
  "damage": 70,
  "mana": 135,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 30,
  "typeSkill": 0
 },
 {
  "type": 535,
  "name": "Reforço de Dormir",
  "level": 1,
  "damage": 1,
  "mana": 27,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 52,
  "typeSkill": 2
 },
 {
  "type": 536,
  "name": "Reforço de Dormir",
  "level": 2,
  "damage": 2,
  "mana": 34,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 52,
  "typeSkill": 2
 },
 {
  "type": 537,
  "name": "Reforço de Dormir",
  "level": 3,
  "damage": 3,
  "mana": 41,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 52,
  "typeSkill": 2
 },
 {
  "type": 538,
  "name": "Reforço de Dormir",
  "level": 4,
  "damage": 4,
  "mana": 48,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 52,
  "typeSkill": 2
 },
 {
  "type": 539,
  "name": "Reforço de Dormir",
  "level": 5,
  "damage": 5,
  "mana": 55,
  "distance": 6,
  "delay": 0,
  "energy": 100,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 52,
  "typeSkill": 2
 },
 {
  "type": 540,
  "name": "Reforço de Relâmpago em cadeia",
  "level": 1,
  "damage": 75,
  "mana": 94,
  "distance": 6,
  "delay": 0,
  "energy": 75,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 53,
  "typeSkill": 0
 },
 {
  "type": 541,
  "name": "Reforço de Relâmpago em cadeia",
  "level": 2,
  "damage": 80,
  "mana": 103,
  "distance": 6,
  "delay": 0,
  "energy": 75,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 53,
  "typeSkill": 0
 },
 {
  "type": 542,
  "name": "Reforço de Relâmpago em cadeia",
  "level": 3,
  "damage": 85,
  "mana": 112,
  "distance": 6,
  "delay": 0,
  "energy": 75,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 53,
  "typeSkill": 0
 },
 {
  "type": 543,
  "name": "Reforço de Relâmpago em cadeia",
  "level": 4,
  "damage": 90,
  "mana": 121,
  "distance": 6,
  "delay": 0,
  "energy": 75,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 53,
  "typeSkill": 0
 },
 {
  "type": 544,
  "name": "Reforço de Relâmpago em cadeia",
  "level": 5,
  "damage": 95,
  "mana": 130,
  "distance": 6,
  "delay": 0,
  "energy": 75,
  "masteryType": 3,
  "skillUseType": 4,
  "magicIcon": 53,
  "typeSkill": 0
 },
 {
  "type": 545,
  "name": "Reforço de Choque do relâmpago",
  "level": 1,
  "damage": 100,
  "mana": 125,
  "distance": 6,
  "delay": 0,
  "energy": 216,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 54,
  "typeSkill": 0
 },
 {
  "type": 546,
  "name": "Reforço de Choque do relâmpago",
  "level": 2,
  "damage": 105,
  "mana": 135,
  "distance": 6,
  "delay": 0,
  "energy": 216,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 54,
  "typeSkill": 0
 },
 {
  "type": 547,
  "name": "Reforço de Choque do relâmpago",
  "level": 3,
  "damage": 110,
  "mana": 145,
  "distance": 6,
  "delay": 0,
  "energy": 216,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 54,
  "typeSkill": 0
 },
 {
  "type": 548,
  "name": "Reforço de Choque do relâmpago",
  "level": 4,
  "damage": 115,
  "mana": 155,
  "distance": 6,
  "delay": 0,
  "energy": 216,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 54,
  "typeSkill": 0
 },
 {
  "type": 549,
  "name": "Reforço de Choque do relâmpago",
  "level": 5,
  "damage": 120,
  "mana": 165,
  "distance": 6,
  "delay": 0,
  "energy": 216,
  "masteryType": 2,
  "skillUseType": 4,
  "magicIcon": 54,
  "typeSkill": 0
 },
 {
  "type": 550,
  "name": "Reforço de Drenar vida",
  "level": 1,
  "damage": 40,
  "mana": 57,
  "distance": 6,
  "delay": 0,
  "energy": 93,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 55,
  "typeSkill": 0
 },
 {
  "type": 551,
  "name": "Reforço de Drenar vida",
  "level": 2,
  "damage": 45,
  "mana": 64,
  "distance": 6,
  "delay": 0,
  "energy": 93,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 55,
  "typeSkill": 0
 },
 {
  "type": 552,
  "name": "Reforço de Drenar vida",
  "level": 3,
  "damage": 50,
  "mana": 71,
  "distance": 6,
  "delay": 0,
  "energy": 93,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 55,
  "typeSkill": 0
 },
 {
  "type": 553,
  "name": "Reforço de Drenar vida",
  "level": 4,
  "damage": 55,
  "mana": 78,
  "distance": 6,
  "delay": 0,
  "energy": 93,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 55,
  "typeSkill": 0
 },
 {
  "type": 554,
  "name": "Reforço de Drenar vida",
  "level": 5,
  "damage": 60,
  "mana": 85,
  "distance": 6,
  "delay": 0,
  "energy": 93,
  "masteryType": 255,
  "skillUseType": 4,
  "magicIcon": 55,
  "typeSkill": 0
 }
];

/** Loader REAL: tenta o skill_*.bmd do asset-server; fallback tabela embutida. */
let _loaded = null, _loading = null;
export function loadSkillAttributes(fetchBinary) {
  if (_loaded) return Promise.resolve(_loaded);
  if (_loading) return _loading;
  const candidates = ['Local/Por/skill_por.bmd', 'Local/por/skill_por.bmd', 'Local/Por/Skill_Por.bmd'];
  _loading = (async () => {
    for (const path of candidates) {
      try {
        const buf = await fetchBinary(path);
        if (!buf) continue;
        const table = decodeSkillAttributeScript(buf);
        const named = table.filter(Boolean).length;
        if (named < 10) throw new Error(`${path}: só ${named} registros legíveis`);
        console.info(`[SkillAttribute] tabela real carregada de ${path}: ${named} skills`);
        _loaded = table;
        return table;
      } catch (e) { /* tenta próximo candidato */ }
    }
    // Fallback: tabela embutida (mesma origem — arquivo real do cliente).
    const table = new Array(SKILL_ATTRIBUTE_COUNT).fill(null);
    for (const row of SKILL_ATTRIBUTE_TABLE) table[row.type] = row;
    console.info('[SkillAttribute] fetch indisponível — tabela embutida (skill_por.bmd real) em uso');
    _loaded = table;
    return table;
  })();
  return _loading;
}
